// Copies the real Assist website and app assets the video uses into
// `public/`, and turns the bundled Hugeicons into a typed module so scenes can
// recolor them. Nothing is downloaded; every file comes from this repository.
import { copyFileSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const web = resolve(root, "../web/public");
const macResources = resolve(root, "../macos/Sources/Assist/Resources");
const publicDir = join(root, "public");
const generatedDir = join(root, "src/generated");

const copies = [
  [join(web, "assist-icon.png"), "brand/assist-icon.png"],
  [join(web, "brands/apple.svg"), "brands/apple.svg"],
  [join(web, "brands/microsoft.svg"), "brands/microsoft.svg"],
  [join(web, "brands/meta.svg"), "brands/meta.svg"],
  [join(web, "brands/amazon.svg"), "brands/amazon.svg"],
  [join(web, "brands/tiktok.svg"), "brands/tiktok.svg"],
  [join(web, "brands/mistral-ai.svg"), "brands/mistral-ai.svg"],
  [join(web, "brands/doordash.svg"), "brands/doordash.svg"],
  [join(web, "videos/notch-modules-demo.mp4"), "videos/notch-modules-demo.mp4"],
  [join(web, "videos/screenshot-editor.mp4"), "videos/screenshot-editor.mp4"],
  [join(web, "videos/voice-annotation.mp4"), "videos/voice-annotation.mp4"],
  [join(web, "videos/clipboard-history.mp4"), "videos/clipboard-history.mp4"],
  [join(macResources, "Fonts/InterVariable.ttf"), "fonts/InterVariable.ttf"]
];

for (const file of readdirSync(join(web, "modules"))) {
  if (file.endsWith(".png")) {
    copies.push([join(web, "modules", file), `modules/${file}`]);
  }
}

// Typing sounds come from Assist's own "Soft" keyboard pack (MIT, kbsim).
for (const file of readdirSync(join(web, "keyboard-sounds/soft"))) {
  copies.push([join(web, "keyboard-sounds/soft", file), `keyboard-sounds/soft/${file}`]);
}

rmSync(publicDir, { recursive: true, force: true });
for (const [from, to] of copies) {
  const target = join(publicDir, to);
  mkdirSync(dirname(target), { recursive: true });
  copyFileSync(from, target);
}

// Hugeicons Stroke Rounded, vendored by the macOS app. The package draws with
// a fixed #141B34 stroke; `currentColor` lets each scene pick the ink.
const iconsDir = join(macResources, "Icons");
const icons = {};
for (const file of readdirSync(iconsDir).sort()) {
  if (!file.endsWith(".svg")) continue;
  const svg = readFileSync(join(iconsDir, file), "utf8")
    .replace(/#141B34/gi, "currentColor")
    .replace(/\s+/g, " ")
    .trim();
  icons[file.replace(/\.svg$/, "")] = svg;
}

mkdirSync(generatedDir, { recursive: true });
writeFileSync(
  join(generatedDir, "hugeicons.ts"),
  `// Generated by scripts/sync-assets.mjs from apps/macos/Sources/Assist/Resources/Icons.\n` +
    `export const HUGEICONS = ${JSON.stringify(icons, null, 2)} as const;\n\n` +
    `export type HugeiconName = keyof typeof HUGEICONS;\n`
);

console.log(`Copied ${copies.length} files into public/ and ${Object.keys(icons).length} icons into src/generated/.`);
